from typing import Any, Generic, TypeVar

TState = TypeVar("TState")

END: str


class StateGraph(Generic[TState]):
    def __init__(self, state_schema: type[TState]) -> None: ...
    def add_node(self, name: str, action: Any, **kwargs: Any) -> "StateGraph[TState]": ...
    def set_entry_point(self, key: str) -> "StateGraph[TState]": ...
    def add_edge(self, start_key: str, end_key: str) -> "StateGraph[TState]": ...
    def compile(self, **kwargs: Any) -> Any: ...
